GET http://localhost:3000/
### Récupération de l'écran d'accueil

GET http://localhost:3000/games
### Récupération de tout les jeux

GET http://localhost:3000/games/category/31
### Récupération des jeux par categories

GET http://localhost:3000/games/platform/6
### Récupération des jeux par plateforme

GET http://localhost:3000/games/520
### Récupération des données d'un jeu

GET http://localhost:3000/games/520/review
### Récupération de toutes les reviews d'un jeu

POST http://localhost:3000/signup
Content-Type: application/json


{
    "pseudo": "CBDF",
    "email": "hhhhhhh@gmail.com",
    "password": "111111",
    "passwordConfirm": "111111"
}
### Inscription d'un membre

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "hhhhhhh@gmail.com",
    "password": "111111"
}
### Login d'un membre

GET http://localhost:3000/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Q0JERg.qVUZu2aHgSwK-lTmFX_-pj8u926B5u0jcIznCaL-Fbc
### Connexion à son profil

POST http://localhost:3000/games/444/review
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Q0JERg.qVUZu2aHgSwK-lTmFX_-pj8u926B5u0jcIznCaL-Fbc

{
            "content":"Génial !!",
            "gameplay_note" : 5,
            "soundtrack_note" : 5,
            "graphism_note" : 5,
            "global_note" : 5,
            "platform" : "PC"
}
### Poster un avis

PATCH http://localhost:3000/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Q0JERg.qVUZu2aHgSwK-lTmFX_-pj8u926B5u0jcIznCaL-Fbc

{
    "picture_url" : "abcdefghij/dpjad.jpg"
}
### Modifier son profil

PATCH http://localhost:3000/games/2/review/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Q0JERg.qVUZu2aHgSwK-lTmFX_-pj8u926B5u0jcIznCaL-Fbc

{
    "content" : "Finalement pas mal ...",
    "global_note": 4
}
### Modifier une review
POST http://localhost:3000/contact
Content-Type: application/json

{
    "email":"superuser@gmail.fr",
    "content":"Le site est top , pouvez-vous rajouter encore plus de fonctionnalités ?"
}
### message pour admin

PATCH http://localhost:3000/games/520/review/1/report
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Q0JERg.qVUZu2aHgSwK-lTmFX_-pj8u926B5u0jcIznCaL-Fbc
### Récupération de toutes les reviews d'un jeu